sonar.verbose=true
sonar.organization=nfu-1
sonar.projectKey=nfu_socity
sonar.projectName=socity
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
